// Generated by ts-to-zod
const { z } = require("zod");

envSchema = z.object({
    newgroundsAppID: z.string().nullable(),
    newgroundsEncryptionKey: z.string().nullable()
});

module.exports = { envSchema };