export { default as State } from "./classes/State";
export { createInputPressHandler } from "./classes/InputPressHandler";
export { createInputTickHandler } from "./classes/InputTickHandler";
export { createSprite } from "./classes/Sprite";
export { default as getInputTickHandlerGroupID } from "./functions/getInputTickHandlerGroupID";
export { default as goToLevel } from "./functions/goToLevel";
export { default as init } from "./functions/init";
export { default as lockCameraToEntity } from "./functions/lockCameraToEntity";
export { default as moveEntity } from "./functions/moveEntity";
export { default as onTick } from "./functions/onTick";
export { default as playSpriteAnimation } from "./functions/playSpriteAnimation";
export { default as stopEntity } from "./functions/stopEntity";
